"""baseline

Revision ID: fcf95c979fb7
Revises: 
Create Date: 2021-06-13 18:31:04.212237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf95c979fb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basic_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('telephone', sa.Unicode(length=20), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('gender', sa.Unicode(length=6), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('max_marks', sa.Integer(), nullable=True),
    sa.Column('basicdetails_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['basicdetails_id'], ['basic_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_from', sa.Date(), nullable=True),
    sa.Column('period_to', sa.Date(), nullable=True),
    sa.Column('degree', sa.String(), nullable=True),
    sa.Column('institute', sa.String(), nullable=True),
    sa.Column('university', sa.String(), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('max_marks', sa.Integer(), nullable=True),
    sa.Column('basicdetails_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['basicdetails_id'], ['basic_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('basicdetails_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['basicdetails_id'], ['basic_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_from', sa.Date(), nullable=True),
    sa.Column('period_to', sa.Date(), nullable=True),
    sa.Column('organisation', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('basicdetails_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['basicdetails_id'], ['basic_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work')
    op.drop_table('skills')
    op.drop_table('education')
    op.drop_table('certifications')
    op.drop_table('basic_details')
    # ### end Alembic commands ###
